import {useEffect,useMemo,useRef,useState} from "react";import {useNavigate,useParams} from "react-router-dom";import {usersSeed,stores} from "../data/data";
export default function Users(){const nav=useNavigate(),{merchantId}=useParams(),[list,setList]=useState(()=>JSON.parse(localStorage.getItem("pchUsers")||"null")||usersSeed),[adding,setAdding]=useState(false),[editing,setEditing]=useState(null),[q,setQ]=useState(""),[roleFilter,setRoleFilter]=useState(""),[storeFilter,setStoreFilter]=useState("all");const currentStore=JSON.parse(localStorage.getItem("pchCurrentStore")||"null")||stores.find(s=>s.id==="STR-0004")||stores[0];const [form,setForm]=useState({username:"",role:"",firstName:"",lastName:"",email:"",phone:"",storeId:currentStore.id,cashboxAccess:true,newPassword:"",resetPassword:"",loginPin:""});const photo=useRef();
const filtered=useMemo(()=>list.filter(u=>(!q||`${u.username} ${u.firstName} ${u.lastName} ${u.email} ${u.storeName}`.toLowerCase().includes(q.toLowerCase()))&&(!roleFilter||u.role===roleFilter)&&(storeFilter==="all"||String(u.storeId)===storeFilter)),[list,q,roleFilter,storeFilter]);
useEffect(()=>localStorage.setItem("pchUsers",JSON.stringify(list)),[list]);
const start=(u=null)=>{setEditing(u?.id||null);setForm(u?{...form,...u,newPassword:"",resetPassword:"",loginPin:""}:{username:"",role:"",firstName:"",lastName:"",email:"",phone:"",storeId:currentStore.id,cashboxAccess:true,newPassword:"",resetPassword:"",loginPin:""});setAdding(true)};
const save=e=>{e.preventDefault();if(!form.username||!form.firstName||!form.lastName||!form.role||!form.email||!form.storeId||(!editing&&form.newPassword.length<8)||(!editing&&!/^\d{6}$/.test(form.loginPin))){alert("Please complete all required fields. Password must be 8+ characters and PIN exactly 6 digits.");return}if(form.resetPassword&&form.resetPassword!==form.newPassword){alert("Reset Password must match Set New Password.");return}const st=stores.find(s=>s.id===form.storeId)||currentStore;const u={id:editing||"USR-"+Date.now(),storeId:st.id,storeName:st.name,username:form.username,firstName:form.firstName,lastName:form.lastName,role:form.role,email:form.email,phone:form.phone,cashboxAccess:form.cashboxAccess,status:"Active"};setList(x=>editing?x.map(v=>v.id===editing?{...v,...u}:v):[...x,u]);localStorage.setItem("pchCurrentUser",JSON.stringify(u));setAdding(false);nav(`/pos-configuration?storeId=${encodeURIComponent(st.id)}&userId=${encodeURIComponent(u.id)}`)};
if(adding)return <UserForm form={form} setForm={setForm} onSubmit={save} onCancel={()=>setAdding(false)} photo={photo} onAddAnother={()=>start()} editing={!!editing}/>;
return <div className="page-content users-page"><section><div className="page-header users-header"><div><div className="breadcrumb-area"><button className="link-button" onClick={()=>nav(merchantId?`/merchants/${merchantId}/stores`:"/stores")}><i className="bi bi-arrow-left"/> Stores</button><span>/</span><span>Users</span></div><h1>Users</h1><p>Manage users associated with the selected store.</p></div><button className="primary-button" onClick={()=>start()}><i className="bi bi-plus-lg"/> Add User</button></div>
<div className="selected-store-card"><div className="selected-store-main"><div className="selected-store-icon"><i className="bi bi-shop"/></div><div className="selected-store-info"><h3>{currentStore.name}</h3><div className="selected-store-meta"><span>Store ID: {currentStore.id}</span><span className="meta-dot">•</span><span>{currentStore.type}</span><span className="meta-dot">•</span><span>{currentStore.location}</span></div></div></div><div className="selected-store-status"><span className="status-title">Status</span><span className="store-active-badge">{currentStore.status||"Active"}</span></div></div>
<div className="users-toolbar"><div className="users-toolbar-left"><div className="user-search"><i className="bi bi-search"/><input placeholder="Search users..." value={q} onChange={e=>setQ(e.target.value)}/></div><select className="store-filter" value={storeFilter} onChange={e=>setStoreFilter(e.target.value)}><option value="all">All Stores</option><option value="STR-0004">Westside Market</option><option value="STR-0005">Westside Market North</option></select></div><select className="role-filter" value={roleFilter} onChange={e=>setRoleFilter(e.target.value)}><option value="">All Roles</option>{["Admin","Shop manager","Manager","Cashier","Staff"].map(r=><option key={r}>{r}</option>)}</select></div>
<div className="users-table-card"><div className="table-wrapper"><table className="users-table"><thead><tr><th>User</th><th>Name</th><th>Role</th><th>Store</th><th>Email</th><th>Phone</th><th>Cashdrawer</th><th>Status</th><th>Action</th></tr></thead><tbody>{filtered.map(u=><tr key={u.id}><td><div className="user-cell"><div className="user-avatar">{u.firstName?.[0]}{u.lastName?.[0]}</div><span className="user-username">{u.username}</span></div></td><td>{u.firstName} {u.lastName}</td><td><span className="role-badge">{u.role}</span></td><td><div className="store-table-cell"><i className="bi bi-shop"/>{u.storeName}</div></td><td>{u.email}</td><td>{u.phone}</td><td>{u.cashboxAccess?<span className="cashbox-enabled">Allowed</span>:<span className="cashbox-disabled">No Access</span>}</td><td><span className="status-badge"><span className="status-dot"/>{u.status}</span></td><td><button className="table-action" onClick={()=>start(u)}><i className="bi bi-pencil"/></button></td></tr>)}</tbody></table></div>{filtered.length===0&&<div className="empty-users"><div className="empty-icon"><i className="bi bi-people"/></div><h3>No users found</h3><p>Add a user to this store to get started.</p><button className="primary-button" onClick={()=>start()}><i className="bi bi-plus-lg"/> Add User</button></div>}</div></section></div>}
function UserForm({form,setForm,onSubmit,onCancel,onAddAnother,photo,editing}){const [showPass,setShowPass]=useState(false),[showPin,setShowPin]=useState(false);const set=(k,v)=>setForm(x=>({...x,[k]:v}));return <div className="page-content users-page"><div className="page-header users-header"><div><div className="breadcrumb-area"><button className="link-button" onClick={onCancel}><i className="bi bi-arrow-left"/> Users</button><span>/</span><span>{editing?"Edit User":"Add User"}</span></div><h1>{editing?"Edit User":"Add User"}</h1><p>Create a user and assign access to the selected store.</p></div><button className="primary-button" onClick={onAddAnother}><i className="bi bi-plus-lg"/> Add User</button></div><form className="user-form" onSubmit={onSubmit}>
<Card icon="person" color="purple" title="User Information" sub="Enter the user's account details."><div className="form-grid two-columns">{field("Username","username","Enter username",true)}<Select label="Role" value={form.role} set={v=>set("role",v)} options={["Admin","Shop manager","Manager","Cashier","Staff"]}/>{field("First Name","firstName","Enter first name",true)}{field("Last Name","lastName","Enter last name",true)}{field("Email","email","name@example.com",true,"email")}{field("User Phone","phone","Enter phone number")}</div></Card>
<Card icon="shop" color="orange" title="Store Access" sub="Define the store and cashdrawer access for this user."><div className="form-grid two-columns"><Select label="Store Name" value={form.storeId} set={v=>set("storeId",v)} options={stores.filter(s=>s.id==="STR-0004"||s.id==="STR-0005").map(s=>`${s.id}||${s.name}`)} values={stores.filter(s=>s.id==="STR-0004"||s.id==="STR-0005").map(s=>s.id)}/><div className="cashbox-access-box"><label className="checkbox-label"><input type="checkbox" checked={form.cashboxAccess} onChange={e=>set("cashboxAccess",e.target.checked)}/><span className="custom-checkbox"/><span className="checkbox-text"><strong>Cashdrawer Access</strong><small>Allow this user to access cashdrawer operations for this store.</small></span></label></div></div></Card>
<Card icon="image" color="blue" title="Profile Photo" sub="Upload a profile image for this user."><div className="profile-upload"><div className="profile-preview"><i className="bi bi-person"/></div><div className="upload-content"><label className="upload-button" htmlFor="profilePhoto"><i className="bi bi-upload"/> Choose Photo</label><input ref={photo} accept="image/png,image/jpeg,image/webp" id="profilePhoto" type="file"/><span className="file-name">JPG, PNG or WEBP · Recommended 200 × 200 px</span></div></div></Card>
<Card icon="shield-lock" color="green" title="Password & Login PIN" sub="Set credentials for the user."><div className="form-grid two-columns">{passwordField("Set New Password","newPassword","Enter new password",form.newPassword,v=>set("newPassword",v),showPass,()=>setShowPass(!showPass),true)}{passwordField("Reset Password","resetPassword","Re-enter password",form.resetPassword,v=>set("resetPassword",v),showPass,()=>setShowPass(!showPass))}{passwordField("Login PIN","loginPin","Enter 6-digit PIN",form.loginPin,v=>set("loginPin",v.replace(/\D/g,"").slice(0,6)),showPin,()=>setShowPin(!showPin),true)}</div></Card>
<div className="form-actions"><button className="cancel-btn" type="button" onClick={onCancel}>Cancel</button><button className="save-next-btn" type="submit">{editing?"Save & Next":"Save & Next"} <i className="bi bi-arrow-right"/></button></div></form></div>;
function field(label,k,ph,req=false,type="text"){return <div className="field"><label>{label} {req&&<span>*</span>}</label><input type={type} value={form[k]} placeholder={ph} required={req} onChange={e=>set(k,e.target.value)}/></div>}
function passwordField(label,k,ph,val,onChange,show,toggle,req){return <div className="field"><label>{label} {req&&<span>*</span>}</label><div className="input-with-action"><input type={show?"text":"password"} value={val} placeholder={ph} required={req} onChange={e=>onChange(e.target.value)}/><button className="input-action" type="button" onClick={toggle}><i className={`bi ${show?"bi-eye-slash":"bi-eye"}`}/></button></div>{k==="newPassword"&&<small className="field-help">Use at least 8 characters.</small>}{k==="loginPin"&&<small className="field-help">Enter exactly 6 digits.</small>}</div>}
function Select({label,value,set,options,values=[]}){return <div className="field"><label>{label} <span>*</span></label><select value={value} onChange={e=>set(e.target.value)} required><option value="">Select {label.toLowerCase()}</option>{options.map((o,i)=>{let [v,t]=o.includes("||")?o.split("||"):[values[i]||o,o];return <option value={v} key={v}>{t}</option>})}</select></div>}
function Card({icon,color,title,sub,children}){return <section className="form-card"><div className="form-card-header"><div className={`section-icon ${color}`}><i className={`bi bi-${icon}`}/></div><div><h2>{title}</h2><p>{sub}</p></div></div><div className="form-card-body">{children}</div></section>}}
